# Generated by Django 3.0.8 on 2020-07-10 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='AuctionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='images')),
                ('category', models.CharField(choices=[('FS', 'Fashion'), ('TY', 'Toys'), ('EL', 'Electronics'), ('AN', 'Antique'), ('HM', 'Home'), ('OT', 'Other')], default='OT', max_length=2)),
                ('active', models.BooleanField(default=False)),
                ('all_bids', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.Bid')),
                ('start_bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auctions.Bid')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='auction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auc', to='auctions.AuctionList'),
        ),
        migrations.AddField(
            model_name='user',
            name='bid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ubid', to='auctions.Bid'),
        ),
        migrations.AddField(
            model_name='user',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmmt', to='auctions.Comment'),
        ),
    ]
