# Generated by Django 3.0.8 on 2020-07-10 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200710_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlist',
            name='auc_comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accmmt', to='auctions.Comment'),
        ),
        migrations.AlterField(
            model_name='auctionlist',
            name='all_bids',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.Bid'),
        ),
        migrations.AlterField(
            model_name='user',
            name='auction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auc', to='auctions.AuctionList'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ubid', to='auctions.Bid'),
        ),
        migrations.AlterField(
            model_name='user',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmmt', to='auctions.Comment'),
        ),
    ]
