# Generated by Django 3.0.8 on 2020-07-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200712_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='image',
            field=models.ImageField(blank=True, default='images/default.jpg', upload_to='images'),
        ),
    ]
