# Generated by Django 3.0.8 on 2020-07-13 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200712_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
