# Generated by Django 3.0.8 on 2020-07-14 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20200713_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='auctionlist',
            name='watchlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.WatchList'),
        ),
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.OneToOneField(default='No', on_delete=django.db.models.deletion.CASCADE, to='auctions.WatchList'),
            preserve_default=False,
        ),
    ]
