# Generated by Django 3.0.8 on 2020-07-14 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20200714_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlist',
            name='watchlist',
        ),
        migrations.RemoveField(
            model_name='user',
            name='watchlist',
        ),
        migrations.DeleteModel(
            name='WatchList',
        ),
    ]
