# Generated by Django 3.0.8 on 2020-07-14 11:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20200714_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlist',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
